accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    BlogListView,
    BlogUpdateView,
    BlogDetailView,
    BlogCreateView,
    BlogDeleteView, # Импортируем представление
)

urlpatterns = [
    path('post/<int:pk>/delete/', # Создаем новый маршрут
    BlogDeleteView.as_view(), name='post_delete'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/edit/',
    BlogUpdateView.as_view(), name='post_edit'),
    path('', BlogListView.as_view(), name='home'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')), # новое добавление
    path('', include('blog.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse # Новый импорт


class Car(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    price = models.TextField()
    year = models.TextField()
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self): # Тут мы создали новый метод
        return reverse('post_detail', args=[str(self.id)])
    
class Image(models.Model):
    post = models.ForeignKey(Car, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/post_images/')

blog/forms.py
# forms.py
from django import forms
from .models import Car, Image

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image',)

class PostForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ('title', )

PostImageFormSet = forms.inlineformset_factory(Car, Image, form=ImageForm, extra=1)

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView # новое
from django.urls import reverse_lazy # импортируем новые методы
from django.shortcuts import render, get_object_or_404, redirect
from .models import Car
from .forms import PostForm, PostImageFormSet

class BlogListView(ListView):
    model = Car
    template_name = 'home.html'


class BlogDetailView(DetailView):
    model = Car
    template_name = 'post_detail.html'


class BlogCreateView(CreateView):
    model = Car
    template_name = 'post_new.html'
    fields = ['title', 'author', 'body']


class BlogUpdateView(UpdateView):
    model = Car
    template_name = 'post_edit.html'
    fields = ['title', 'body']


class BlogDeleteView(DeleteView): # Создание нового класса
    model = Car
    template_name = 'post_delete.html'
    success_url = reverse_lazy('home')
def post_detail(request, pk):
    post = get_object_or_404(Car, pk=pk)
    image_formset = PostImageFormSet(instance=post)

    if request.method == 'POST':
        post_form = PostForm(request.POST, instance=post)
        if post_form.is_valid():
            post = post_form.save()
            image_formset = PostImageFormSet(request.POST, request.FILES, instance=post)
            if image_formset.is_valid():
                image_formset.save()
                return redirect('post_detail', pk=post.pk)
    else:
        post_form = PostForm(instance=post)

templates/base.html
{% load static %}

<html>
  <head>
    <title>Django blog</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
    rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <!-- Include Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<!-- Include Bootstrap JS and Popper.js -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 </head>
  <body class="bg-dark">
    <div>
      <header>
        <div class="nav-left">
          <h1><a href="{% url 'home' %}"class="text-warning"font size="5" color="red" face="Arial">SutochnoKLD</a></h1>
        </div>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="#">Главная</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
              
              <li class="nav-item active">
                <a class="nav-link" href="url vigoda.html" class="text-primary">Выгодная покупка</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="" class="text-primary">О нас</a>
              </li>
              
             


             
              
            </ul>
            <form class="form-inline">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" wfd-id="id5">
              <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>

      </header>
      <style>
        /* base.css */

body {
    font-family: 'Source Sans Pro', sans-serif;
    margin: 0;
    padding: 0;
    background: #2d2d2d;
    color: #fff;
}

.container {
    margin-top: 20px;
}

header {
    background-color: #1d1d1d;
    color: #61dafb;
    padding: 1em;
    text-align: center;
}

h1 a {
    color: #61dafb;
    text-decoration: none;
}

.navbar {
    background-color: #1d1d1d;
}

.navbar-brand {
    color: #61dafb;
}

.navbar-toggler-icon {
    background-color: #61dafb;
}

.navbar-nav .nav-item .nav-link {
    color: #fff;
}

.navbar-nav .nav-item .nav-link:hover {
    color: #61dafb;
}

.nav-right a {
    color: #61dafb;
    text-decoration: none;
}

.content-container {
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
    background-color: #2d2d2d;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
    color: #fff; /* Новый цвет текста для контраста */
}

footer {
    background-color: #1d1d1d;
    color: #61dafb;
    text-align: center;
    padding: 1em;
    position: fixed;
    bottom: 0;
    width: 100%;
}

/* Additional Styles for Better Appearance */
.content-container {
    margin-top: 20px;
}

.navbar-brand {
    font-size: 1.5em;
    font-weight: bold;
}

.navbar-nav .nav-item .nav-link {
    padding: 10px 15px;
}

.btn-outline-light {
    border-color: #61dafb;
    color: #61dafb;
}

.btn-outline-light:hover {
    background-color: #61dafb;
    color: #2d2d2d;
}

.text-primary {
    color: #61dafb;
}

.text-light {
    color: #fff;
}

.text-dark {
    color: #2d2d2d;
}
      </style>
    {% block content %}
    {% endblock content %}
    </div>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<body>

<div class="text-center">
  {% for post in object_list %}
  <div class="post-entry">
    <h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>
    <div class="col-sm">
      <img src="{{ post.image_set.first.image.url }}" alt="{{ post.title }}" class="img-fluid m-3" width="300px;">
    </div>
    <p class="text-light">{{ post.body }}</p>

    
          
      

    <style text> 
      /* Media Query for low resolution  Tablets, Ipads */ 
             @media (min-width: 481px) and (max-width: 767px) { 
                 body { 
                     font-size: 2.5rem; 
                 } 
             } 

             /* Media Query for Tablets Ipads portrait mode */ 
             @media (min-width: 768px) and (max-width: 1024px){ 
                 body { 
                     font-size: 2rem; 
                 } 
             } 

             /* Media Query for Laptops and Desktops */ 
             @media (min-width: 1025px) and (max-width: 1280px){ 
                 body { 
                     font-size: 1.5rem; 
                     padding: 0px 100px; 
                 } 
             } 

             /* Media Query for Large screens */ 
             @media (min-width: 1281px) { 
                 body { 
                                   font-size: 1rem; 
                                   padding: 0px 300px; 
                 } 
             } 
    </style>

  </div>
  {% endfor %}
</div>
{% endblock content %}
</body>

templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete post</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ post.title }}"?</p>
      <input type="submit" value="Confirm" />
    </form>
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
<!-- post_detail.html -->
<h1 class="text-center text-warning "  >{{ car.title }}</h1>
<h3 class="text-center text-light " style=" padding-left: 60px; padding-right: 60px; margin-bottom: 30px ">{{ car.year }}</h3>

<div id="image-carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        {% for image in car.image_set.all %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <center>
                  <img src="{{ image.image.url }}" class="d-block w-20" alt="Image">
                </center>
            </div>
        {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#image-carousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#image-carousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<!-- Include necessary Bootstrap CSS and JS files for the carousel -->

{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit post</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock content %}